# Generated by Django 3.2 on 2021-12-09 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211209_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Идентификатор места'),
            preserve_default=False,
        ),
    ]
