# Generated by Django 3.2 on 2021-12-09 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='Путь к файлу с описанием'),
            preserve_default=False,
        ),
    ]
