# Generated by Django 3.2 on 2021-12-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='slug',
        ),
    ]
