# Generated by Django 3.2 on 2021-12-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_place_id_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details',
        ),
    ]
