# Generated by Django 3.2 on 2021-12-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'slug', 'latitude', 'longitude')},
        ),
    ]
