# Generated by Django 3.2 on 2022-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placephoto',
            name='index',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
